apiVersion: v2
appVersion: 0.10.0
description: A Helm chart for Spica
home: https://spicaengine.com
icon: https://spicaengine.com/assets/icons/icon-512x512.png
keywords:
- cloud-functions
- spica-engine
- development-engine
- content-management-system
maintainers:
- email: dev@spicaengine.com
  name: Spica Maintainers
- email: thesayyn@gmail.com
  name: thesayyn
name: spica
sources:
- https://github.com/spica-engine/spica
type: application
version: 0.10.0
